[package]
name = "warikan"
version = "0.1.0"
edition = "2024"

[lib]
name = "lib"
path = "src/lib.rs"

[dependencies]
rstest = "0.25.0"

[dev-dependencies]
criterion = "0.5"

[profile.release]
debug = true

[[bench]]
name = "benchmark"
harness = false
