version: '3'
services:
  app:
    container_name: app
    build: .
    ports:
      - 3333:3000
    depends_on:
      db:
        condition: service_healthy
    restart: always
  db:
    image: postgres:16.3-alpine3.20
    container_name: pgsql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CHANGEME
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'postgres' ]
      interval: 1s
      timeout: 5s
      retries: 20
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/pgsql
  adminer:
    image: adminer:4.8.1-standalone
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
