name: Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
    paths-ignore:
      - '**/README.md'
  pull_request:
    paths-ignore:
      - '**/README.md'

env:
  RUST_BACKTRACE: 1

jobs:
  checks:
    name: cargo build / cargo fmt / cargo clippy / cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@v2
        if: ${{ github.event_name == 'pull_request' }} # 一番長い job にのみセットしたいため
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build --all-features
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-features -- -D warnings
      - run: cargo test --all-features
